CREATE TABLE [dbo].[companies] (
    [id]                     INT            IDENTITY (1, 1) NOT NULL,
    [user_id]                NVARCHAR (200) NOT NULL,
    [name]                   VARCHAR (100)  NOT NULL,
    [business_type]          VARCHAR (25)   NOT NULL,
    [registered_address_id]  INT            NULL,
    [operational_address_id] INT            NULL,
    [affiliate]              VARCHAR (100)  NULL,
    [nationality]            VARCHAR (50)   NULL,
    [contact_firstname]      VARCHAR (50)   NULL,
    [contact_lastname]       VARCHAR (50)   NULL,
    [contact_phone]          VARCHAR (15)   NOT NULL,
    [year_incorporated]      INT            NULL,
    [rc_number]              VARCHAR (50)   NULL,
    [tin_number]             VARCHAR (50)   NULL,
    [no_staff]               INT            NULL,
    [no_expatriate]          INT            NULL,
    [total_asset]            VARCHAR (50)   NULL,
    [yearly_revenue]         VARCHAR (50)   NULL,
    [accident_report]        VARCHAR (MAX)  NULL,
    [training_program]       VARCHAR (MAX)  NULL,
    [mission_vision]         VARCHAR (MAX)  NULL,
    [hse]                    VARCHAR (MAX)  NULL,
    [Date]                   DATETIME       NULL,
    [hseDoc]                 BIT            NULL,
    [accident]               INT            NULL,
    [elps_id]                INT            NULL,
    [DPR_Id]                 NVARCHAR (50)  NULL,
    [CompanyCode]            NVARCHAR (50)  NULL,
    [CompanyEmail]           VARCHAR (80)   NULL,
    [Avarta]                 VARCHAR (200)  NULL,
    [isFirstTime]            BIT            NULL,
    [ActiveStatus]           BIT            NULL,
    [CreatedAt]              DATETIME       NULL,
    [UpdatedAt]              DATETIME       NULL,
    [DeleteStatus]           BIT            NULL,
    [DeletedBy]              INT            NULL,
    [DeletedAt]              DATETIME       NULL,
    [Address]                VARCHAR (200)  NULL,
    [City]                   VARCHAR (50)   NULL,
    [StateName]              VARCHAR (50)   NULL,
    [LocationId]             INT            NULL,
    [RoleId]                 INT            NULL,
    CONSTRAINT [PK_company_id] PRIMARY KEY CLUSTERED ([id] ASC)
);

