CREATE TABLE [dbo].[Facilities] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [Name]               NVARCHAR (250) NOT NULL,
    [CompanyId]          INT            NOT NULL,
    [CategoryId]         INT            NULL,
    [AddressId]          INT            NOT NULL,
    [CoordinateId]       INT            NULL,
    [Date]               DATETIME       NOT NULL,
    [NoofDriveIn]        INT            NOT NULL,
    [NoOfDriveOut]       INT            NOT NULL,
    [NoOfPumps]          INT            NULL,
    [NoOfTanks]          INT            NULL,
    [MaxCapacity]        INT            NULL,
    [Elps_Id]            INT            NULL,
    [LGA]                VARCHAR (90)   NULL,
    [ContactName]        NVARCHAR (70)  NULL,
    [ContactNumber]      NVARCHAR (50)  NULL,
    [IdentificationCode] NVARCHAR (50)  NULL,
    [CategoryCode]       NVARCHAR (50)  NULL,
    [FirstOperationYear] INT            NULL,
    [city]               VARCHAR (40)   NULL,
    [StateName]          VARCHAR (30)   NULL,
    [CountryName]        VARCHAR (40)   NULL,
    [address_1]          NVARCHAR (100) NULL,
    [DeletedStatus]      BIT            NULL,
    [DeletedAt]          INT            NULL,
    CONSTRAINT [PK_Facilities] PRIMARY KEY CLUSTERED ([Id] ASC)
);

