CREATE TABLE [dbo].[Legacies] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [CompId]             NVARCHAR (15)  NOT NULL,
    [LicenseNo]          NVARCHAR (50)  NOT NULL,
    [CompName]           NVARCHAR (150) NULL,
    [CompAddress]        NVARCHAR (250) NULL,
    [FacilityAddress]    NVARCHAR (250) NULL,
    [LGA]                NVARCHAR (100) NULL,
    [State]              NVARCHAR (50)  NULL,
    [LPG_FIG_KG]         FLOAT (53)     NULL,
    [LPG_Tanks]          INT            NULL,
    [AGOVol]             FLOAT (53)     NULL,
    [AGO_Tanks]          INT            NULL,
    [PMSVol]             FLOAT (53)     NULL,
    [PMS_Tanks]          INT            NULL,
    [DPKVol]             FLOAT (53)     NULL,
    [DPK_Tanks]          INT            NULL,
    [BitumenTanks]       INT            NULL,
    [BitumenVol]         FLOAT (53)     NULL,
    [ATKTanks]           INT            NULL,
    [ATKVol]             FLOAT (53)     NULL,
    [BaseOilTanks]       INT            NULL,
    [BaseOilVol]         FLOAT (53)     NULL,
    [LubeOilGreaseTanks] INT            NULL,
    [LubeOilGreaseVol]   FLOAT (53)     NULL,
    [FuelOilTanks]       INT            NULL,
    [FuelOilVol]         FLOAT (53)     NULL,
    [Issue_Date]         NVARCHAR (50)  NULL,
    [Exp_Date]           NVARCHAR (50)  NULL,
    [Maj]                INT            NULL,
    [AppType]            NVARCHAR (50)  NULL,
    [IsUsed]             BIT            NULL,
    [DateUsed]           DATETIME       NULL,
    [Status]             VARCHAR (50)   NULL,
    [DeleteStatus]       BIT            NULL,
    [FacilityName]       VARCHAR (300)  NULL,
    [City]               VARCHAR (80)   NULL,
    [LandMeters]         DECIMAL (18)   NULL,
    [IsPipeline]         BIT            NULL,
    [IsHighTension]      BIT            NULL,
    [IsHighway]          BIT            NULL,
    [ContactName]        VARCHAR (50)   NULL,
    [ContactPhone]       VARCHAR (30)   NULL,
    [Products]           VARCHAR (300)  NULL,
    [UpdatedAt]          DATETIME       NULL,
    [DeletedAt]          DATETIME       NULL,
    [ApprovedBy]         INT            NULL,
    [Comment]            VARCHAR (100)  NULL,
    [AppDocId]           INT            NULL,
    [CompElpsDocId]      INT            NULL,
    [DocSource]          VARCHAR (300)  NULL,
    [DropStaffId]        INT            NULL,
    [ApprovedAt]         DATETIME       NULL,
    [CreatedAt]          DATETIME       NULL,
    [DeletedBy]          INT            NULL,
    CONSTRAINT [PK_Legacy_1] PRIMARY KEY CLUSTERED ([Id] ASC, [CompId] ASC)
    --CONSTRAINT [PK_Legacy_1] PRIMARY KEY CLUSTERED ([Id] ASC, [CompId] ASC, [LicenseNo] ASC)
);

